//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkınSoft_Password_Manager.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passwords
    {
        public int PasswordID { get; set; }
        public string ImageUrl { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
    }
}
